apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nodejs
        image: node:16
        ports:
        - containerPort: 3000
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: apps
spec:
  scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
type: Resource
resource:
  name: cpu
  target:
type: Utilization
averageUtilization: 70
